using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.IO;

namespace AuthenticationServer.Models.Services
{
    public class Log
    {
        public static void LogRequest_Rate(RateResponse request)
        {
            //SqlConnection connLog = new SqlConnection(Configuration.UpsRateSqlConnection);
            //connLog.Open();

            //SqlCommand cmdLog = new SqlCommand();
            //cmdLog.Connection = connLog;
            //cmdLog.CommandType = CommandType.StoredProcedure;
            //cmdLog.CommandText = "Log_Quote";
            //SqlParameter source = new SqlParameter("@Source", SqlDbType.VarChar, 50);
            //SqlParameter plantCode = new SqlParameter("@PlantCode", SqlDbType.VarChar, 50);
            //SqlParameter destinationAddress1 = new SqlParameter("@DestinationAddress1", SqlDbType.VarChar, 50);
            //SqlParameter destinationAddress2 = new SqlParameter("@DestinationAddress2", SqlDbType.VarChar, 50);
            //SqlParameter destinationAddress3 = new SqlParameter("@DestinationAddress3", SqlDbType.VarChar, 50);
            //SqlParameter destinationCity = new SqlParameter("@DestinationCity", SqlDbType.VarChar, 50);
            //SqlParameter destinationState = new SqlParameter("@DestinationState", SqlDbType.VarChar, 50);
            //SqlParameter destinationPostalCode = new SqlParameter("@DestinationPostalCode", SqlDbType.VarChar, 50);
            //SqlParameter weight = new SqlParameter("@Weight", SqlDbType.Int);
            //SqlParameter lftg_pu = new SqlParameter("@LFTG_PU", SqlDbType.Bit);
            //SqlParameter lftg_d = new SqlParameter("@LFTG_D", SqlDbType.Bit);
            //SqlParameter lap = new SqlParameter("@LAP", SqlDbType.Bit);
            //SqlParameter lapu = new SqlParameter("@LAPU", SqlDbType.Bit);
            //SqlParameter resd = new SqlParameter("@RESD", SqlDbType.Bit);
            //SqlParameter ind = new SqlParameter("@IND", SqlDbType.Bit);
            //SqlParameter ipu = new SqlParameter("@IPU", SqlDbType.Bit);
            //SqlParameter ss = new SqlParameter("@SS", SqlDbType.Bit);
            //SqlParameter stpo = new SqlParameter("@STPO", SqlDbType.Bit);
            //SqlParameter service01 = new SqlParameter("@Service01", SqlDbType.VarChar, 50);
            //SqlParameter carrier01 = new SqlParameter("@Carrier01", SqlDbType.VarChar, 50);
            //SqlParameter rate01 = new SqlParameter("@Rate01", SqlDbType.VarChar, 50);
            //SqlParameter service02 = new SqlParameter("@Service02", SqlDbType.VarChar, 50);
            //SqlParameter carrier02 = new SqlParameter("@Carrier02", SqlDbType.VarChar, 50);
            //SqlParameter rate02 = new SqlParameter("@Rate02", SqlDbType.VarChar, 50);
            //SqlParameter service03 = new SqlParameter("@Service03", SqlDbType.VarChar, 50);
            //SqlParameter carrier03 = new SqlParameter("@Carrier03", SqlDbType.VarChar, 50);
            //SqlParameter rate03 = new SqlParameter("@Rate03", SqlDbType.VarChar, 50);
            //SqlParameter service04 = new SqlParameter("@Service04", SqlDbType.VarChar, 50);
            //SqlParameter carrier04 = new SqlParameter("@Carrier04", SqlDbType.VarChar, 50);
            //SqlParameter rate04 = new SqlParameter("@Rate04", SqlDbType.VarChar, 50);
            //SqlParameter service05 = new SqlParameter("@Service05", SqlDbType.VarChar, 50);
            //SqlParameter carrier05 = new SqlParameter("@Carrier05", SqlDbType.VarChar, 50);
            //SqlParameter rate05 = new SqlParameter("@Rate05", SqlDbType.VarChar, 50);
            //SqlParameter service06 = new SqlParameter("@Service06", SqlDbType.VarChar, 50);
            //SqlParameter carrier06 = new SqlParameter("@Carrier06", SqlDbType.VarChar, 50);
            //SqlParameter rate06 = new SqlParameter("@Rate06", SqlDbType.VarChar, 50);
            //SqlParameter service07 = new SqlParameter("@Service07", SqlDbType.VarChar, 50);
            //SqlParameter carrier07 = new SqlParameter("@Carrier07", SqlDbType.VarChar, 50);
            //SqlParameter rate07 = new SqlParameter("@Rate07", SqlDbType.VarChar, 50);
            //SqlParameter service08 = new SqlParameter("@Service08", SqlDbType.VarChar, 50);
            //SqlParameter carrier08 = new SqlParameter("@Carrier08", SqlDbType.VarChar, 50);
            //SqlParameter rate08 = new SqlParameter("@Rate08", SqlDbType.VarChar, 50);
            //SqlParameter service09 = new SqlParameter("@Service09", SqlDbType.VarChar, 50);
            //SqlParameter carrier09 = new SqlParameter("@Carrier09", SqlDbType.VarChar, 50);
            //SqlParameter rate09 = new SqlParameter("@Rate09", SqlDbType.VarChar, 50);
            //SqlParameter service10 = new SqlParameter("@Service10", SqlDbType.VarChar, 50);
            //SqlParameter carrier10 = new SqlParameter("@Carrier10", SqlDbType.VarChar, 50);
            //SqlParameter rate10 = new SqlParameter("@Rate10", SqlDbType.VarChar, 50);
            //SqlParameter service11 = new SqlParameter("@Service11", SqlDbType.VarChar, 50);
            //SqlParameter carrier11 = new SqlParameter("@Carrier11", SqlDbType.VarChar, 50);
            //SqlParameter rate11 = new SqlParameter("@Rate11", SqlDbType.VarChar, 50);
            //SqlParameter service12 = new SqlParameter("@Service12", SqlDbType.VarChar, 50);
            //SqlParameter carrier12 = new SqlParameter("@Carrier12", SqlDbType.VarChar, 50);
            //SqlParameter rate12 = new SqlParameter("@Rate12", SqlDbType.VarChar, 50);
            //SqlParameter service13 = new SqlParameter("@Service13", SqlDbType.VarChar, 50);
            //SqlParameter carrier13 = new SqlParameter("@Carrier13", SqlDbType.VarChar, 50);
            //SqlParameter rate13 = new SqlParameter("@Rate13", SqlDbType.VarChar, 50);
            //SqlParameter service14 = new SqlParameter("@Service14", SqlDbType.VarChar, 50);
            //SqlParameter carrier14 = new SqlParameter("@Carrier14", SqlDbType.VarChar, 50);
            //SqlParameter rate14 = new SqlParameter("@Rate14", SqlDbType.VarChar, 50);
            //SqlParameter service15 = new SqlParameter("@Service15", SqlDbType.VarChar, 50);
            //SqlParameter carrier15 = new SqlParameter("@Carrier15", SqlDbType.VarChar, 50);
            //SqlParameter rate15 = new SqlParameter("@Rate15", SqlDbType.VarChar, 50);
            //SqlParameter service16 = new SqlParameter("@Service16", SqlDbType.VarChar, 50);
            //SqlParameter carrier16 = new SqlParameter("@Carrier16", SqlDbType.VarChar, 50);
            //SqlParameter rate16 = new SqlParameter("@Rate16", SqlDbType.VarChar, 50);
            //SqlParameter service17 = new SqlParameter("@Service17", SqlDbType.VarChar, 50);
            //SqlParameter carrier17 = new SqlParameter("@Carrier17", SqlDbType.VarChar, 50);
            //SqlParameter rate17 = new SqlParameter("@Rate17", SqlDbType.VarChar, 50);
            //SqlParameter service18 = new SqlParameter("@Service18", SqlDbType.VarChar, 50);
            //SqlParameter carrier18 = new SqlParameter("@Carrier18", SqlDbType.VarChar, 50);
            //SqlParameter rate18 = new SqlParameter("@Rate18", SqlDbType.VarChar, 50);
            //SqlParameter service19 = new SqlParameter("@Service19", SqlDbType.VarChar, 50);
            //SqlParameter carrier19 = new SqlParameter("@Carrier19", SqlDbType.VarChar, 50);
            //SqlParameter rate19 = new SqlParameter("@Rate19", SqlDbType.VarChar, 50);
            ////SqlParameter service20 = new SqlParameter("@Service20", SqlDbType.VarChar, 50);
            ////SqlParameter carrier20 = new SqlParameter("@Carrier20", SqlDbType.VarChar, 50);
            ////SqlParameter rate20 = new SqlParameter("@Rate20", SqlDbType.VarChar, 50);

            //source.Value = request.Source;
            //plantCode.Value = request.PlantCode;
            //destinationAddress1.Value = request.DestinationAddress1;
            //destinationAddress2.Value = request.DestinationAddress2;
            //destinationAddress3.Value = request.DestinationAddress3;
            //destinationCity.Value = request.DestinationCity;
            //destinationState.Value = request.DestinationState;
            //destinationPostalCode.Value = request.DestinationPostalCode;
            //weight.Value = request.Weight;
            //lftg_pu.Value = request.LFTG_PU;
            //lftg_d.Value = request.LFTG_D;
            //lap.Value = request.LAP;
            //lapu.Value = request.LAPU;
            //resd.Value = request.RESD;
            //ind.Value = request.IND;
            //ipu.Value = request.IPU;
            //ss.Value = request.SS;
            //stpo.Value = request.STPO;
            //service01.Value = request.Service[0];
            //carrier01.Value = request.Carrier[0];
            //rate01.Value = request.Rate[0];
            //service02.Value = request.Service[1];
            //carrier02.Value = request.Carrier[1];
            //rate02.Value = request.Rate[1];
            //service03.Value = request.Service[2];
            //carrier03.Value = request.Carrier[2];
            //rate03.Value = request.Rate[2];
            //service04.Value = request.Service[3];
            //carrier04.Value = request.Carrier[3];
            //rate04.Value = request.Rate[3];
            //service05.Value = request.Service[4];
            //carrier05.Value = request.Carrier[4];
            //rate05.Value = request.Rate[4];
            //service06.Value = request.Service[5];
            //carrier06.Value = request.Carrier[5];
            //rate06.Value = request.Rate[5];
            //service07.Value = request.Service[6];
            //carrier07.Value = request.Carrier[6];
            //rate07.Value = request.Rate[6];
            //service08.Value = request.Service[7];
            //carrier08.Value = request.Carrier[7];
            //rate08.Value = request.Rate[7];
            //service09.Value = request.Service[8];
            //carrier09.Value = request.Carrier[8];
            //rate09.Value = request.Rate[8];
            //service10.Value = request.Service[9];
            //carrier10.Value = request.Carrier[9];
            //rate10.Value = request.Rate[9];
            //service11.Value = request.Service[10];
            //carrier11.Value = request.Carrier[10];
            //rate11.Value = request.Rate[10];
            //service12.Value = request.Service[11];
            //carrier12.Value = request.Carrier[11];
            //rate12.Value = request.Rate[11];
            //service13.Value = request.Service[12];
            //carrier13.Value = request.Carrier[12];
            //rate13.Value = request.Rate[12];
            //service14.Value = request.Service[13];
            //carrier14.Value = request.Carrier[13];
            //rate14.Value = request.Rate[13];
            //service15.Value = request.Service[14];
            //carrier15.Value = request.Carrier[14];
            //rate15.Value = request.Rate[14];
            //service16.Value = request.Service[15];
            //carrier16.Value = request.Carrier[15];
            //rate16.Value = request.Rate[15];
            //service17.Value = request.Service[16];
            //carrier17.Value = request.Carrier[16];
            //rate17.Value = request.Rate[16];
            //service18.Value = request.Service[17];
            //carrier18.Value = request.Carrier[17];
            //rate18.Value = request.Rate[17];
            //service19.Value = request.Service[18];
            //carrier19.Value = request.Carrier[18];
            //rate19.Value = request.Rate[18];
            ////service20.Value = request.Service[19];
            ////carrier20.Value = request.Carrier[19];
            ////rate20.Value = request.Rate[19];

            //cmdLog.Parameters.Add(source);
            //cmdLog.Parameters.Add(plantCode);
            //cmdLog.Parameters.Add(destinationAddress1);
            //cmdLog.Parameters.Add(destinationAddress2);
            //cmdLog.Parameters.Add(destinationAddress3);
            //cmdLog.Parameters.Add(destinationCity);
            //cmdLog.Parameters.Add(destinationState);
            //cmdLog.Parameters.Add(destinationPostalCode);
            //cmdLog.Parameters.Add(weight);
            //cmdLog.Parameters.Add(lftg_pu);
            //cmdLog.Parameters.Add(lftg_d);
            //cmdLog.Parameters.Add(lap);
            //cmdLog.Parameters.Add(lapu);
            //cmdLog.Parameters.Add(resd);
            //cmdLog.Parameters.Add(ind);
            //cmdLog.Parameters.Add(ipu);
            //cmdLog.Parameters.Add(ss);
            //cmdLog.Parameters.Add(stpo);
            //cmdLog.Parameters.Add(service01);
            //cmdLog.Parameters.Add(carrier01);
            //cmdLog.Parameters.Add(rate01);
            //cmdLog.Parameters.Add(service02);
            //cmdLog.Parameters.Add(carrier02);
            //cmdLog.Parameters.Add(rate02);
            //cmdLog.Parameters.Add(service03);
            //cmdLog.Parameters.Add(carrier03);
            //cmdLog.Parameters.Add(rate03);
            //cmdLog.Parameters.Add(service04);
            //cmdLog.Parameters.Add(carrier04);
            //cmdLog.Parameters.Add(rate04);
            //cmdLog.Parameters.Add(service05);
            //cmdLog.Parameters.Add(carrier05);
            //cmdLog.Parameters.Add(rate05);
            //cmdLog.Parameters.Add(service06);
            //cmdLog.Parameters.Add(carrier06);
            //cmdLog.Parameters.Add(rate06);
            //cmdLog.Parameters.Add(service07);
            //cmdLog.Parameters.Add(carrier07);
            //cmdLog.Parameters.Add(rate07);
            //cmdLog.Parameters.Add(service08);
            //cmdLog.Parameters.Add(carrier08);
            //cmdLog.Parameters.Add(rate08);
            //cmdLog.Parameters.Add(service09);
            //cmdLog.Parameters.Add(carrier09);
            //cmdLog.Parameters.Add(rate09);
            //cmdLog.Parameters.Add(service10);
            //cmdLog.Parameters.Add(carrier10);
            //cmdLog.Parameters.Add(rate10);
            //cmdLog.Parameters.Add(service11);
            //cmdLog.Parameters.Add(carrier11);
            //cmdLog.Parameters.Add(rate11);
            //cmdLog.Parameters.Add(service12);
            //cmdLog.Parameters.Add(carrier12);
            //cmdLog.Parameters.Add(rate12);
            //cmdLog.Parameters.Add(service13);
            //cmdLog.Parameters.Add(carrier13);
            //cmdLog.Parameters.Add(rate13);
            //cmdLog.Parameters.Add(service14);
            //cmdLog.Parameters.Add(carrier14);
            //cmdLog.Parameters.Add(rate14);
            //cmdLog.Parameters.Add(service15);
            //cmdLog.Parameters.Add(carrier15);
            //cmdLog.Parameters.Add(rate15);
            //cmdLog.Parameters.Add(service16);
            //cmdLog.Parameters.Add(carrier16);
            //cmdLog.Parameters.Add(rate16);
            //cmdLog.Parameters.Add(service17);
            //cmdLog.Parameters.Add(carrier17);
            //cmdLog.Parameters.Add(rate17);
            //cmdLog.Parameters.Add(service18);
            //cmdLog.Parameters.Add(carrier18);
            //cmdLog.Parameters.Add(rate18);
            //cmdLog.Parameters.Add(service19);
            //cmdLog.Parameters.Add(carrier19);
            //cmdLog.Parameters.Add(rate19);
            ////cmdLog.Parameters.Add(service20);
            ////cmdLog.Parameters.Add(carrier20);
            ////cmdLog.Parameters.Add(rate20);            

            //cmdLog.ExecuteNonQuery();
            //connLog.Close();
        }

        public static void LogRequest_Rate(string username, string address, string city, string state, string zip, string country, string request, string response, string direction)
        {
            SqlConnection connLog = new SqlConnection(Configuration.UpsRateSqlConnection);
            connLog.Open();

            SqlCommand cmdLog = new SqlCommand();
            cmdLog.Connection = connLog;
            cmdLog.CommandType = CommandType.StoredProcedure;
            cmdLog.CommandText = "LogRequest_Rate";

            SqlParameter pUserName = new SqlParameter("@UserName", SqlDbType.VarChar, 50);
            SqlParameter pTargetUrl = new SqlParameter("@TargetUrl", SqlDbType.VarChar, 200);
            SqlParameter pAddress = new SqlParameter("@Address", SqlDbType.VarChar, 200);
            SqlParameter pCity = new SqlParameter("@City", SqlDbType.VarChar, 200);
            SqlParameter pState = new SqlParameter("@State", SqlDbType.VarChar, 50);
            SqlParameter pZip = new SqlParameter("@Zip", SqlDbType.VarChar, 50);
            SqlParameter pCountry = new SqlParameter("@Country", SqlDbType.VarChar, 2);
            SqlParameter pRequestXml = new SqlParameter("@RequestXml", SqlDbType.NText);
            SqlParameter pResponseXml = new SqlParameter("@ResponseXml", SqlDbType.NText);
            //SqlParameter pApiSource = new SqlParameter("@APISource", SqlDbType.VarChar, 50);
            SqlParameter pRequestId = new SqlParameter("@RequestId", SqlDbType.Int);

            pUserName.Value = username;
            pTargetUrl.Value = Configuration.UPSShopRatesURL;
            pAddress.Value = address;
            pCity.Value = city;
            pState.Value = state;
            pZip.Value = zip;
            pCountry.Value = country;
            pRequestXml.Value = request;
            pResponseXml.Value = response;
            //pApiSource.Value = apisource;
            pRequestId.Direction = ParameterDirection.Output;

            cmdLog.Parameters.Add(pUserName);
            cmdLog.Parameters.Add(pTargetUrl);
            cmdLog.Parameters.Add(pAddress);
            cmdLog.Parameters.Add(pCity);
            cmdLog.Parameters.Add(pState);
            cmdLog.Parameters.Add(pZip);
            cmdLog.Parameters.Add(pCountry);
            cmdLog.Parameters.Add(pRequestXml);
            cmdLog.Parameters.Add(pResponseXml);
            //cmdLog.Parameters.Add(pApiSource);
            cmdLog.Parameters.Add(pRequestId);

            cmdLog.ExecuteNonQuery();

            //RateRequestId = Convert.ToInt32(pRequestId.Value);

            connLog.Close();
        }


    }

}